---
title       : Reproducible pitch
subtitle    : 
author      : Ming-tsan Peng
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        :  selfcontained  # {, standalone , draft}
knit        : slidify::knit2slides
github:
   user: mtp22peng
   repo: home_slides
---

## Outlines

1. Summary of the data set "galton"
2. Interactive histogram of child height 
 

--- .class #id 

## galton data and summary


```{r}
data(galton)
summary(galton)
```

--- .class #id 

## Histogram of the child height


```{r}
hist(galton$child, xlab='child height', col='lightblue',main='Histogram')
```


--- .class #id 

## select a mean equal to 70 and put this line on top of the Histogram. Mean square error is calculated.


```{r}

      hist(galton$child, xlab='child height', col='lightblue',main='Histogram')
      mu <- 70
      lines(c(mu, mu), c(0, 200),col="red",lwd=5)
      mse <- mean((galton$child - mu)^2)
      text(63, 150, paste("mu = ", mu))
      text(63, 140, paste("MSE = ", round(mse, 2)))
```

